### ISSUE TITLE
Support for Middleman 4.0.0?

### ISSUE THREAD

**Issue by mmasnjak** [plasticine/middleman-imageoptim#46]
Since upgrading to OS X El Capitan, I had to start using Middleman 4.0.0 RC1. I know Middleman 4 isn't released yet, but I was wondering if there was a plan to support it soon-ish.

**Comment by nlsrchtr** [comment]
+1

**Comment by pusewicz** [comment]
:+1:

**Comment by ibarral** [comment]
+1

**Comment by plasticine** [comment]
Hey everyone,

I’ve not been using Middleman for much lately and have been pretty stretched, so MM 4.x is not something that has really been on my radar. If anyone really wants this and is prepared to get their hands dirty I would be very much open to a PR, otherwise it will have to wait until I have some free time again.

**Comment by osabate** [comment]
:+1:  Any alternatives in the meantime?

**Comment by nukos** [comment]
+1

**Comment by craigmdennis** [comment]
+1

**Comment by hubertron** [comment]
+1

**Comment by frankmarineau** [comment]
+1

**Comment by mschneider** [comment]
+1

**Comment by fcalderan** [comment]
+1

**Comment by isaiahgrey93** [comment]
+1

**Comment by craigmdennis** [comment]
In the meantime, I've put a repo together using the new external pipeline and Gulp (which includes image optimisation) https://github.com/craigmdennis/middleman-gulp-starter

**Comment by chenware** [comment]
+1

**Comment by kgish** [comment]
+1

**Comment by kmanzana** [comment]
Anyone working on this?  If not I might pick this up as it would be nice to have on a personal project.

**Comment by timroeleveld** [comment]
+1

**Comment by Jed-Lehmann** [comment]
+1

**Comment by chrishough** [comment]
+1

**Comment by chrishough** [comment]
@kmanzana did you fork it already?

**Comment by kmanzana** [comment]
@chrishough, I haven't and won't have time in the near future.  I'm assume by the lack of response to my question that no one else is working on it though.

**Comment by juliendargelos** [comment]
+1

**Comment by kmanzana** [comment]
@Dmanz21, let's work on this together in the near future.

**Comment by hello-jason** [comment]
There is nothing directly actionable on this issue, merely a consensus that folks want support for v4. I propose we close this ticket and, instead, report the issues we find with v4 compatibility. Such as this... #51

**Comment by fxmountain** [comment]
Not supporting middleman 4.0 yet? :thinking:

**Comment by hello-jason** [comment]
@fxmountain the master branch of middleman-imageoptim does support 4.0, but the maintainer has not cut a new gem release yet. See this comment for 4.0 support - https://github.com/plasticine/middleman-imageoptim/issues/51#issuecomment-296867750

Secondly, I feel this ticket can be closed since the `master` branch does support 4.0. There is a separate issue for getting an updated gem on #56. @mmasnjak agree to close?

**Comment by mmasnjak** [comment]
👍
